BaSP-m2023/baru-megarocket-server

src/controllers/trainer.js
src/routes/trainer.js

i made the delete and find by id for trainers. I changed the name of trainer in models to Trainer.js.

BaSP-MR-11: delete and find by ID created

---

.eslintrc.js
.husky/pre-commit
babel.config.js
jest.config.js
jest.setup.js
package-lock.json
package.json
src/app.js
src/index.js
src/tests/activitys.test.js
src/tests/admins.test.js
src/tests/classes.test.js
src/tests/members.test.js
src/tests/subscriptions.test.js
src/tests/super-admins.test.js
src/tests/trainers.test.js

-  Setting up of prject. 
-  Files restructuring. 
- package.json updated
-  jest.config.js and jest.setup.js files added. 
- babel.config.js file created.
- .eslintrc.js file updated
- src/index.js updated
- app.js created

BaSP-MR-18: project set up

---

src/controllers/class.js
src/models/Class.js

Class schema update and population

BaSP-MR-27: Class schema update and population

---

Readme.md
src/controllers/class.js
src/routes/class.js
src/seeds/classes.js
src/tests/classes.test.js
src/validations/class.js

- seeds defined
- update endpoint tests
- logic delete endpoint tests
- validation fixes
- restore method and endpoint added
- readme file endpoints updated

BaSP-MR-35: endpoints put delete test and fixes

---

src/tests/trainers.test.js

made the get by ID and delete.
https://trello.com/c/nGlchw8e/34-trainer-unit-test-delete-getbyid

BaSP-MR-34: test endpoint trainer

---

jest.setup.js
src/controllers/super-admins.js
src/seeds/super-admins.js
src/tests/super-admins.test.js

- Adding seeds
- Get and Get by ID methods tests
- Post method tests
- Put method tests
- Delete method tests

 BaSP-MR-24: Super Admin - Tests for Get, Post, Put and Delete methods  

---

src/controllers/subscription.js
src/models/Subscription.js
src/routes/subscription.js
src/seeds/subscriptions.js
src/tests/subscriptions.test.js
src/validations/subscription.js

Population and Interconnections for subscriptions (members and class connection).
Unit tests for create a subscription (created with all the fields and valid parameters).
Unit tests for delete a subscription (delete an existing subscription).

BaSp-MR-#39: Subscription - Unit test - CREATE & DELETE Checks

---

src/controllers/admins.js

Modify the GetById function of the Admins controller to return all admin data

BaSP-MR-90: Modify GetById function in admins controller

---

src/controllers/subscription.js
src/seeds/subscriptions.js
src/tests/subscriptions.test.js

Added populate for get-By-Id and simplified tests to make them work with the new changes

BaSP-MR-89: Subscription controller added populate

---

src/models/Activity.js
src/tests/activitys.test.js
src/validations/activity.js

Fix joi validations in activities
Now add and edit have the same length requirements for the description of the activities (at least 20 chars)
And remove the require atribute from the update validations

BaSP-MR-84: Fix validations in activities

---

src/controllers/super-admins.js
src/tests/super-admins.test.js

Fixed the server's response of the delete success in superadmin

BaSP-MR-88: Superadmin

---

src/controllers/activity.js
src/routes/index.js
src/tests/activitys.test.js
src/validations/activity.js

BUGS reported by QAs fixed.
- Inconsistency on return structure in GET ALL, PUT, POST AND DELETE methods
- Added a right message to the description validation.
- Set the route in the plural form.
- Tests fixed to the new changes.

BaSP-MR-88: Fixes on activities

---

src/controllers/member.js
src/models/Member.js
src/tests/members.test.js

Fix response from all endpoints from members with proper template
Fix post method. Now we can add a new member with a membership of "Only classes"
And make new tests that will fit this new estructure of the response

BaSP-MR-112: Fix members response from all endpoints

---

src/tests/trainers.test.js
src/validations/trainer.js

Fixed the validations and error responses in Trainers resource, when create or edit a trainer.

BaSP-MR-114: Hotfix trainers validations and responses

---

src/controllers/member.js

Fix response messages in put and deletes methods from members resource

BaSP-MR-115: Fix messages

---

src/controllers/class.js
src/models/Class.js
src/routes/class.js
src/seeds/classes.js
src/tests/classes.test.js
src/validations/class.js

These bugs were fixed:
and in the responses msg was changed to message to unify

BaSP-MR-88: changes to the server in class resource

---

src/controllers/admins.js
src/models/Admin.js
src/validations/admins.js

https://trello.com/c/wVzOfV2M
Add response message when edit and add admins.
Changes in validations and admin model.

BaSP-MR-88: Changes in admins resource

---

src/controllers/activity.js
src/models/Activity.js
src/seeds/activitys.js
src/tests/activitys.test.js
src/tests/admins.test.js
src/validations/activity.js

Development to respond [Trello-MR#127](https://trello.com/c/qre3EIbg)
New
- Added new `trainers` attribute on activities schema. This allow us to add trainers when an activity needs to be created.
- Added validations in Joi
- Added trainers populate on GET, POST and PUT methods
- Tests added to cover the new implementation
Fixes
- There was an error on the tests from admin. Now works

BaSP-MR-127: Refactor on activities for Admin rol

---

package-lock.json
package.json
src/helper/firebase/index.js
src/middlewares/authMiddleware.js

Added setup for firebase and added files for middlewares and file auth controller.

BaSP-MR-145: Firebase setup

---

src/helper/firebase/index.js

Changed environment variables they were wrong.

BaSP-MR-164: hotfix for change enviroment variables 

---

src/controllers/trainer.js
src/models/Trainer.js
src/routes/index.js
src/validations/trainer.js

Changed functions in controller trainers, creating new trainer now creates a new user in firebase and mongodb. 
Changes in update controller function

BaSP-MR-155: Trainer Server

---

src/controllers/member.js
src/models/Member.js
src/validations/members.js

Implement firebase in members
Now when create a new member we add a firebase id (in order to link to firebase data base). So we are using 2 data bases, 1 in mongo and 1 in firebase.
And now we cant edit neither mail or password from the edit endpoint (this functionality will be developed later when we add the email/password recovery)
Add delete method to the firebase db

BaSP-Feature-MR154: Implement firebase members

---

src/controllers/super-admins.js
src/helper/firebase/index.js
src/models/SuperAdmin.js
src/routes/index.js
src/validations/super-admins.js

Add firebase to add and remove superAdmins, this adds a role to the registered user and to be able to identify what type of role they fulfill within the page. Besides, check if you have registered users with the same email

BaSP-MR-149: Super admin firebase

---

src/controllers/auth.js
src/routes/auth.js
src/routes/index.js

https://trello.com/c/ndtzj9j6
This feature validates that the user logging in exists in the database, if successful it returns the user data

BaSP-MR-160: Auth controller

---

src/controllers/admins.js
src/controllers/member.js
src/controllers/super-admins.js
src/controllers/trainer.js
src/helper/firebase/index.js
src/middlewares/authMiddleware.js
src/models/Admin.js
src/models/Member.js
src/models/SuperAdmin.js
src/models/Trainer.js
src/routes/admins.js
src/routes/index.js
src/seeds/admins.js
src/tests/admins.test.js
src/validations/admins.js

Development to respond [Trello-MR#153](https://trello.com/c/NBgtGxiQ)
- Now the POST method add the new admin user in the Firebase db
- The DELETE method also delete the admin user from Firebase
- Implemented private route on admins routes
- Logical delete from admins
- Updated the firebase uid in controllers and models of SuperAdmin, Admin, Trainer and member due to consistency
- Header fixed on middleware

BaSP-MR-153: Admin with firebase

---

src/routes/index.js

https://trello.com/c/zDdCUfkJ
This feature adds the middleware to the routes of each user

BaSP-MR-166: Middleware

---

src/controllers/subscription.js

Fixed success update subscription message. Before it had no message, now it has a "Subscription Updated" message.

Hotfix-MR-137: Subscription update message

---

src/routes/index.js
src/routes/member.js

https://trello.com/c/93tflHCz
In this hotfix the middleware was removed from the post path, so that a member can register

BaSP-MR-171: Hotfix member routes

---

src/controllers/admins.js
src/controllers/member.js
src/controllers/trainer.js

Now when creating or updating this users, it shouldn't let create/update them if there is a DNI assigned to another user of the same rol.

BaSP-MR-183: DNI Validations (Member, Trainer, Admin)

---

src/controllers/class.js
src/models/Class.js
src/seeds/classes.js
src/tests/classes.test.js
src/validations/class.js

Classes:
-Added an available property, to check 
-Now it validates that the class has to start at an o'clock hour.
-Sunday is not anymore an elegible day.

BaSP-MR-198: Classes validations

---

src/controllers/subscription.js

Fixed population for trainers and activities because it only contains id and more information about these entities cannot be accessed.
Before: 
After:

hotfix-MR-195: Fix populate for subscription classes

---

src/controllers/trainer.js
src/routes/trainer.js

The update and create functions for the trainer have been fixed, where some parameters were being passed incorrectly.

BaSP-MR-215: fix put and create of trainer

---

src/controllers/admins.js

Changed handler from admin to remove admin because there was a problem with the handler to remove an admin and the structure was changed

BaSP-MR-208: Change deleteAdmin controller

---

src/controllers/member.js

A validation was added so that there are not 2 identical emails since it was validated with firebase but not with mongo and it made the server crash

BaSP-MR-223: Fix validation for email sign up

---

src/validations/activity.js

Fix validations for activities
Now we can add any character to the descriptions, not only letters

BaSP-MR-240: Fix activities validations
